# Use the Ubuntu image as the base
FROM ubuntu:latest

# Install necessary packages, including MariaDB
#RUN apt-get update && \
#    apt-get install -y mariadb-server

# Set the root password for MariaDB (change this as needed)
#RUN echo "mariadb-server-10.5 mysql-server/root_password password yourpassword" | debconf-set-selections && \
#    echo "mariadb-server-10.5 mysql-server/root_password_again password yourpassword" | debconf-set-selections

# Expose MariaDB port (optional)
#EXPOSE 3306

# Start the MariaDB service (optional)
#CMD ["service", "mysql", "start"]
