version: '3.8'

services:
  # app:
  #  image: your-app-image:tag  # If you're using a pre-built image, specify it here
  #  depends_on:
  #    - mariadb
  #  environment:
  #    CODESPACES: "********"
  #  ports:
  #    - "5000:5000"
  #  volumes:
  #    - "/.codespaces/agent/mount:/.codespaces/bin:rw"
  #    - "/mnt/containerTmp:/tmp:rw"
  #    - "/var/lib/docker/codespacemount/workspace/codespaces-blank/.devcontainer:/workspace:rw"

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    restart: always
